  version: '3.5'
  
  
  services:
    angular-service:
      container_name: hrms-front-end-container
      build: ./
      volumes: 
      - './:/usr/src/app'
      ports: 
        - "4200:80"
      command: npm install && npm start